apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.yaml
  - nbsetupkey.yaml
  - nbsetupkey-jupyterhub.yaml
  - external-secret.yaml
  - external-secret-jupyterhub.yaml
  - external-secret-postgres.yaml

helmCharts:
  - name: kubernetes-operator
    repo: https://netbirdio.github.io/helms
    version: 0.1.13
    releaseName: netbird-operator
    namespace: netbird
    valuesFile: operator-values.yaml
    includeCRDs: true
