
managementURL: https://api.netbird.io

netbirdAPI:
  keyFromSecret:
    name: netbird-secret
    key: NB_API_KEY

webhook:
  enableCertManager: true
  failurePolicy: Fail

ingress:
  enabled: true
  kubernetesAPI:
    enabled: true
  namespacedNetworks: false
  allowAutomaticPolicyCreation: true
  router:
    enabled: true
    replicas: 1